<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Geoip
 */
?>
<?php
/**
 * @var \Amasty\Geoip\Block\Adminhtml\Settings\Import $this
 */
?>
<button id="am-import"
        class="action-default scalable" <?= $this->getImportFilesAvailable() ? '' : 'disabled="disabled"' ?>
        data-ui-id="widget-button-0" type="button" title="<?= __('Import') ?>">
    <span><?= __('Import') ?></span>
</button>
<br/>
<br/> var/amasty/geoip/GeoLite2-City-Blocks-IPv4.csv
<div class="<?= $this->getBlockFileExist() ? 'amgeoip-files-available' : 'amgeoip-files-unavailable' ?> "></div>
<br/> var/amasty/geoip/GeoLite2-City-Blocks-IPv6.csv
<div class="<?= $this->getBlockV6FileExist() ? 'amgeoip-files-available' : 'amgeoip-files-unavailable' ?> "></div>
<br/> var/amasty/geoip/GeoLite2-City-Locations-en.csv
<div class="<?= $this->getLocationFileExist() ? 'amgeoip-files-available' : 'amgeoip-files-unavailable' ?> "></div>
<br/>
<div class="progressbar">
    <div class="am_processer_container"><span class="begin"></span>

        <div class="am_line">
            <div class="am_processer" style="width: <?= $this->getWidth() ?>%"><span>&nbsp</span></div>
        </div>
        <span class="<?= $this->getImportedClass() ?>"></span></div>
    <span class="import"><div class="bubble"><?= __('Import') ?></div></span><span class="completed"><div
                class="bubble"><?= __("Completed") ?></div></span>
</div>
<br/> <?= $this->getImportDate() ?>
<script type="text/javascript">
    require([
        'jquery',
        'Amasty_Geoip/js/import'
    ], function ($) {
        var imp = $('#am-import');

        imp.amGeoip({
            importItems: <?= $this->getConfig(); ?>,
            type: 'import'
        });

    });

</script>

