<?php 
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Checkoutspage v2.x.x
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
*/
 ?>
<?php if ($block->canDisplay() && $coupon = $block->getCoupon()) { ?>
	<div class="csp-coupon" >
		<div class="csp-coupon-message"><h2><?php echo $block->getCouponMessage(); ?></h2></div>
		<div class="csp-coupon-background" <?php if ($block->isBackground() ){ ?> style="background:url('<?php echo $block->getBackground(); ?>');" <?php } ?>>
			<div class="csp-coupon-code"><?php echo $coupon ?></div>
		</div>
	</div>

<?php } ?>