<?php 
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Checkoutspage v2.x.x
 * @copyright   Copyright (c) 2015-2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
*/
 ?>
<div class="csp-page-title thank">
	<h1 class="csp-h1"><?php echo __('Thank You!'); ?></h1>
	<h3 class="csp-h3"><?php echo __('Your Order Has Been Processed'); ?></h3>
</div>
<style>
	.page-title-wrapper{display:none}
</style>