<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'list';
    $imageDisplayArea = 'category_page_list';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        $attr = $_product->getResource()->getAttribute('brand')->getFrontend()->getValue($_product);
                        $_helperImage = $this->helper('Magento\Catalog\Helper\Image');
                        $imageUrl = $_helperImage->init($_product, 'product_page_image_small')->setImageFile($_product->getSmallImage())->resize(380)->getUrl();
                        ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                           <span class="product-image-container"
                                 style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
                                <span class="product-image-wrapper"
                                      style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100) ?>%;">
                                <img src="<?php echo $imageUrl; ?>"
                                     class="product-image-photo"
                                     width="<?php echo $block->getWidth(); ?>"
                                     height="<?php echo $block->getHeight(); ?>"
                                     alt="<?php echo $block->getLabel() ?>"/></span>
                            </span>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <div class="product-attribute"><?php echo $attr?></div>
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <div class="input-qty">
                                                    <div product-id="<?php echo $_product->getId(); ?>" class="product-list decrease-qty">+</div>
                                                    <input type="number" name="qty" id="qty_<?php echo $_product->getId(); ?>" maxlength="12" value="<?php /* @escapeNotVerified */ echo '1' ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" />
                                                    <div product-id="<?php echo $_product->getId(); ?>" class="product-list increase-qty">-</div>
                                                </div>
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="action">
                                                        <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="quick-order action tocart primary" product-id="<?php echo $_product->getId(); ?>">
                                                            <span><?= /* @escapeNotVerified */ __('+') ?></span>
                                                        </button>
                                                         <a class="remove"><?php echo __('Remove'); ?></a>
                                                    </div>
                                                <?php endif; ?>
                                            </form>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>

    <script type="text/x-magento-init">
    {
        "*": {
            "Convert_Quickorder/js/default":{}
        }
    }
    </script>
<?php endif; ?>
