<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<?php
$blockObj= $block->getLayout()->createBlock('Convert\FreeShip\Block\Cart\Sidebar');
?>
<div data-block="minicart" class="minicart-wrapper">
  <a class="action showcart desktop " href="<?= /* @escapeNotVerified */ $block->getShoppingCartUrl() ?>"
   data-bind="scope: 'minicart_content'">
     <span class="text"><?= /* @escapeNotVerified */ __('My Cart') ?></span>
     <span class="counter qty empty"
     data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
     <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
     <span class="counter-label">
      <!-- ko if: getCartParam('summary_count') -->
      <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
      <!-- ko i18n: 'items' --><!-- /ko -->
      <!-- /ko --> 
    </span>
  </span> 
  </a>
  <a class="action mobile " href="<?= /* @escapeNotVerified */ $block->getShoppingCartUrl() ?>"
   data-bind="scope: 'minicart_content'">
     <span class="text"><?= /* @escapeNotVerified */ __('My Cart') ?></span>
     <span class="counter qty empty"
     data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
     <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
     <span class="counter-label">
      <!-- ko if: getCartParam('summary_count') -->
      <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
      <!-- ko i18n: 'items' --><!-- /ko -->
      <!-- /ko --> 
    </span>
  </span>
  </a>
<?php if ($block->getIsNeedToDisplaySideBar()): ?>
  <div class="block block-minicart"
  data-role="dropdownDialog"
  data-mage-init='{"dropdownDialog":{
  "appendTo":"[data-block=minicart]",
  "triggerTarget":".showcart",
  "timeout": "2000",
  "closeOnMouseLeave": false,
  "closeOnEscape": true,
  "triggerClass":"active",
  "parentClass":"active",
  "buttons":[]}}'>
  <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
    <!-- ko template: getTemplate() --><!-- /ko -->
  </div>
  <?= $block->getChildHtml('minicart.addons') ?>
</div>
<?php endif ?>
<script>
  window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
</script>
<script>
 maxpriceShipping = <?= /* @escapeNotVerified */ $blockObj->getAmountFreeship() ?>;
 stt = <?= /* @escapeNotVerified */ $blockObj->checkconfig() ?>;
 currencysymbol = '<?= /* @escapeNotVerified */ $blockObj->getCurrentCurrencySymbol() ?>';
</script>
<script type="text/x-magento-init">
  {
    "[data-block='minicart']": {
    "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
  },
  "*": {
  "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
}
}
</script>
</div>

<script>
    require([
        'jquery',
        'scrollbar'
   ], function($){

    var windowWidth = $(window).width();
    $('.minicart-wrapper .action.showcart').click(function(){
      setTimeout(function() {
        if(windowWidth >= 768){
          $('.minicart-items-wrapper').addClass('scrollbar-inner');
          if($('ol#mini-cart').height() > 430) {
            $('.minicart-items-wrapper').scrollbar();
          }
        }
        

      }, 500);
    });

    var loop = setInterval(function() {
      if(windowWidth >= 768){
        if($('.minicart-wrapper .product-item-details .product.options').length > 0) {
          $('.minicart-wrapper .product-item-details .product.options').click(function(){
            $('.minicart-items-wrapper').addClass('scrollbar-inner');
            $('.minicart-items-wrapper').scrollbar();
          });
        }
      }
    }, 1000);
  });
</script>
