<?php
/** @var \Convert\CategoryThumbnail\Block\HomeFavorites $blockCategory */
$blockCategory = $block->getLayout()->createBlock('Convert\CategoryThumbnail\Block\HomeFavorites');
$cat_id = $this->getData('category_id');
$_category = $blockCategory->getCategoryFavorites($cat_id);
$subCategories = $_category->getChildrenCategories();
/** @var \Convert\CategoryThumbnail\Helper\Data $objectHelper */
$objectHelper = $this->Helper('Convert\CategoryThumbnail\Helper\Data');
$mediaUrl = $objectHelper->getMediaUrl();
$count = count($subCategories);

?>
<?php foreach ($subCategories as $subCategory): ?>
    <?php $categoryName = $subCategory->getName(); ?>
    <div class="mega-category-with-thumbnail">
        <div class="item">
            <?php $category = $objectHelper->getLoadCategory($subCategory->getId()); ?>
            <?php if ($category->getCategoryThumbnail()): ?>
                <a class="cat_img" href="<?php echo $category->getUrl() ?>">
                    <img src="<?php echo $category->getCategoryThumbnail() ?>" title="<?php echo $categoryName; ?>" alt="<?php echo $categoryName; ?>"/>
                </a>
            <?php else: ?>
                <a class="cat_img" href="<?php echo $category->getUrl() ?>">
                    <img src="<?php echo $mediaUrl . 'default_thumbnail.jpg' ?>" title="<?php echo $categoryName; ?>" alt="<?php echo $categoryName; ?>"/>
                </a>
            <?php endif; ?>
        </div>
        <div class="content">
            <div class="text">
                <a class="cat_name" href="<?php echo $category->getUrl() ?>"><?php echo $categoryName; ?></a>
            </div>
        </div>
    </div>
<?php endforeach; ?>