<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

$helper = $this->helper('Convert\Catalog\Helper\Data');
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$bundleHelper = $this->helper('Convert\Catalog\Helper\BundleHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
			__('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
	<?= $block->getToolbarHtml() ?>
	<?= $block->getAdditionalHtml() ?>
	<?php
	if ($block->getMode() == 'grid') {
		$viewMode = 'grid';
		$imageDisplayArea = 'category_page_grid';
		$showDescription = false;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	} else {
		$viewMode = 'list';
		$imageDisplayArea = 'category_page_list';
		$showDescription = true;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	}
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos = $block->getPositioned();
	$count = 0;
	?>
    <div class="products wrapper <?= /* @escapeNotVerified */
	$viewMode ?> products-<?= /* @escapeNotVerified */
	$viewMode ?>">
        <ol class="products list items product-items">
			<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			<?php foreach ($_productCollection as $_product):
				$count++;

				?>

                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
					$viewMode ?>">
						<?php
						$product = $helper->getLoadProduct($_product->getId());
						// get value attribute
						$datalimit = $product->getData('limited_and_new');
						$dataSale = $product->getData('sale_product');
						// get text attribute
						$attrSale = $product->getResource()->getAttribute('sale_product');
						$attrLimit = $product->getResource()->getAttribute('limited_and_new');
						if ($attrSale->usesSource()) {
							$valueSale = $attrSale->getSource()->getOptionText($dataSale);
						}

						if ($attrLimit->usesSource()) {
							$valueLimit = $attrLimit->getSource()->getOptionText($datalimit);
						}

						?>
                        <div class="list-attribute-product">
							<?php
							if (isset($valueLimit) && $valueLimit == "Limited") {
								?>
                                <div class="my-attribute attribute-limit-new-<?= strtoupper($valueLimit) ?>">
									<?= $valueLimit ?>
                                </div>
								<?php
							}
							if (isset($valueSale)) {
								?>
                                <div class="my-attribute attribute-sale-product-<?= $valueSale ?>">
									<?= $valueSale ?>
                                </div>
								<?php
							}
							?>
                        </div>
						<?php
						$productImage = $block->getImage($_product, $imageDisplayArea);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>
						<?php // Product Image
						?>
                        <a href="<?= /* @escapeNotVerified */
						$_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <div class="align-attribute-new">
								<?php
								if (isset($valueLimit) && $valueLimit == "New") {
									?>
                                    <div class="my-attribute attribute-limit-new-<?= strtoupper($valueLimit) ?>">
										<?= $valueLimit ?>
                                    </div>
									<?php
								}
								?>
                            </div>
                            <div class="product-item-detail">
								<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
								<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
                                <span class="stamped-product-reviews-badge" data-id="<?php echo $_product->getId() ?>"
                                      style="display: block;"></span>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
									   $_product->getProductUrl() ?>">
										<?= /* @escapeNotVerified */
										$_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>

								<?= /* @escapeNotVerified */
								$block->getProductPrice($_product) ?>
								<?= $block->getProductDetailsHtml($_product) ?>
                            </div>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= /* @NoEscape */
											      $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
												$postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */
												Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */
												$postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
												<?= $block->getBlockHtml('formkey') ?>
                                                <?php $buttonTitle = __('Add to Bag');?>
                                                <?php if($_product->getTypeId() == 'bundle') : ?>
                                                    <?php if($bundleHelper->checkCanAddToCart($_product)):?>
                                                        <div style="display:block; height: 0; visibility: hidden">
                                                            <?= $bundleHelper->getBundleOptionsHtml($_product); ?>
                                                        </div>
                                                    <?php else: $buttonTitle = __('Select Options') ?>
                                                    <?php endif;?>

                                                <?php endif;?>
                                                <button type="submit"
                                                        title="<?= $buttonTitle ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */
                                                        $buttonTitle ?></span>
                                                </button>
                                            </form>
										<?php else: ?>
											<?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */
														__('In stock') ?></span></div>
											<?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */
														__('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
                                    </div>
                                </div>
                                <div class="product description product-item-description">
                                    <div class="text-description"><?= /* @escapeNotVerified */
										$_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></div>
                                    <a href="<?= /* @escapeNotVerified */
									$_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
									$_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */
										__('View details') ?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
			<?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
		<?= $block->getToolbarHtml() ?>
    </div>

	<?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */
			$_product->getSku() ?>"
                }
            }
        }






        </script>
	<?php endif; ?>
<?php endif; ?>
