<div class="reviews-and-links">
  <span class="stamped-product-reviews-badge" data-style-color-star="#4AC1E0" data-id="<?php echo $this->getProductId() ?>" data-url="<?php echo $this->getProductUrl() ?>" data-product-sku="<?php echo $this->getProductSku() ?>"></span>
  <span class="view-real-results">
    <a href="<?php echo $this->getUrl('real-results'); ?>" title="View real results"><?php echo 'View real results'?></a>
  </span>
</div>

