<?php 
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Checkoutspage v2.x.x
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
*/
 ?>

 <?php  $_item = $block->getItem(); ?>
 <tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td>
        <?php echo $this->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail', ['width' => '70'])->toHtml(); ?>
    </td>
    <td class="col name csp-product-info" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>

        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>

        <table>
            <tr class="items-sku">
                <td>
                    <?php echo __('SKU:'); ?>
                </td>
                <td>
                    <?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?>
                </td>
            </tr>
            <tr class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <td class="item">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered:'); ?></span>
                </td>
                <td>
                    <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
                </td>
            <?php endif; ?>
            </tr>
        </table>

        <?php if ( $_options = $_item->getProductOptions()): ?>

            <dl class="item-options">

            <?php foreach ($_options['bundle_options'] as $_option): ?>

                    <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>

                    <?php foreach ($_option['value'] as $key => $value): ?>
                        <dd>
                            <?php echo $value['qty']; ?> x <?php echo $value['title']; ?>
                            <?php if (isset($_option['value'][$key + 1])): ?>
                                <br />
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>

            <?php endforeach; ?>

            </dl>
        <?php endif; ?>

    </td>
    <td class="col items-qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
    <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
        <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
    <?php endif; ?>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
