<?php 
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Checkoutspage v2.x.x
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
*/
 ?>

 <?php  $_item = $block->getItem(); ?>
 <tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td>
        <?php echo $this->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail', ['width' => '70'])->toHtml(); ?>
    </td>
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <table>
        <?php foreach ($_options as $_option) : ?>
            <tr>
                <td><?php echo $block->escapeHtml($_option['label']) ?></td>
                <td>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd>
                            <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                        </dd>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </table>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>

        <table>
            <tr class="items-sku">
                <td>
                    <?php echo __('SKU:'); ?>
                </td>
                <td>
                    <?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?>
                </td>
            </tr>
            <tr class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <td class="item">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered:'); ?></span>
                </td>
                <td>
                    <span class="content"><?php /* @escapeNotVerified */ echo (int)$block->getItem()->getQtyOrdered() ?></span>
                </td>
            <?php endif; ?>
            </tr>
        </table>
    </td>
    <td class="col items-qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
    <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
        <span class="content"><?php /* @escapeNotVerified */ echo (int)$block->getItem()->getQtyOrdered() ?></span>
    <?php endif; ?>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
