<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
$helper = $this->helper('Convert\Catalog\Helper\Data');
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
		<?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */
		$filtered ?>">
            <strong data-role="title"><?= /* @escapeNotVerified */
				__('Filter by') ?></strong>
        </div>
        <div class="block-content filter-content">
            <div class="filter-content-area">
                <div class="filter-content-top">
					<?= $block->getChildHtml('state') ?>

					<?php if ($block->getLayer()->getState()->getFilters()): ?>
                        <div class="block-actions filter-actions">
                            <a href="<?= /* @escapeNotVerified */
							$block->getClearUrl() ?>"
                               class="action clear filter-clear"><span><?= /* @escapeNotVerified */
									__('Clear All') ?></span></a>
                        </div>
					<?php endif; ?>

                </div>


				<?php $wrapOptions = false; ?>
				<?php foreach ($block->getFilters() as $filter): ?>
			<?php if ($filter->getItemsCount()): ?>
			<?php if (!$wrapOptions): ?>
                <strong role="heading" aria-level="2"
                        class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */
					__('Shopping Options') ?></strong>
                <div class="filter-options" id="narrow-by-list" data-role="content"
                     data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
					<?php $wrapOptions = true;
					endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
						<?php
						if ($filter->getName() == 'Category') {
							?>
                            <div data-role="title" class="filter-options-title title-first"><?= /* @escapeNotVerified */
								__('PONi Range') ?></div>
                            <div data-role="content" class="filter-options-content no-check">
                                <ol class="items">
                                   <!-- <li class="item">
                                        <a href="<?/*= $block->getBaseUrl() . "shop" */?>"><?/*= __('Shop All') */?></a>
                                    </li>-->
									<?php
									$listCategory = $helper->getCategoryConvert();
									if (count($listCategory) > 0) {
										foreach ($listCategory as $value) {
											?>
                                            <li class="item <?php echo $value['url'] ?>">
                                                <a href="<?= $block->getBaseUrl() . "" . $value['url_parent'] . "/" . $value['url'] ?>"><?= $value['name'] ?></a>
                                            </li>

											<?php
										}
									}
									?>
                                </ol>
                            </div>
						<?php } else { ?>
                            <div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */
								__(strtolower($filter->getName())) ?></div>
                            <div data-role="content" class="filter-options-content checked"><?= /* @escapeNotVerified */
								$block->getChildBlock('renderer')->render($filter) ?></div>
							<?php
						}
						?>
                    </div>
					<?php endif; ?>
					<?php endforeach; ?>
					<?php if ($wrapOptions): ?>
                </div>
			<?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
				<?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
