<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
use Magento\Framework\App\Action\Action;
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
<?php foreach ($items as $_item): ?>
    <div class="product-item-info">
        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
            <?= $block->getImage($_item, $image)->toHtml() ?>
        </a>
        <div class="product-item-details">
                <?php if ($showWishlist || $showCompare || $showCart): ?>
                    <div class="product-item-actions">
                        <?php if ($showCart): ?>
                            <div class="actions-primary">
                                <?php if ($_item->isSaleable()): ?>
                                        <?php
                                            $blockListProduct = $this->getLayout()->createBlock(\Magento\Catalog\Block\Product\ListProduct::class);
                                            $postParams = $blockListProduct->getAddToCartPostParams($_item);
                                        ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add').'uenc/' . $postParams['data'][Action::PARAM_NAME_URL_ENCODED] . '/product/' . $postParams['data']['product'] ?>" method="post">


                                            <div class="align-swatch">
                                            <?php if($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){
                                                $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                                    echo $swatchBlock->setProduct($_item)->toHtml();                           
                                            } ?></div>

                                            <strong class="product-item-name">
                                                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                                   class="product-item-link"> 
                                                    <?= $block->escapeHtml($_item->getName()) ?>
                                                </a>
                                            </strong>
                                            <?php echo $block->getProductPriceHtml($_item, $type);?>

                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            

                                            <div class="align-summary">
                                             <span class="stamped-product-reviews-badge" data-id="<?php echo $_item->getId() ?>" style="display: block;"></span>
                                            </div>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to cart') ?></span>
                                            </button>
                                        </form>
                                <?php else: ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($showWishlist || $showCompare): ?>
                            <div class="actions-secondary" data-role="add-to-links">
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                    <a href="#"
                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                    </a>
                                <?php endif; ?>
                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
        </div>
    </div>
<?php endforeach ?>
<?php endif;?>
