<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

$helper = $this->helper('Convert\Catalog\Helper\Data');

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_chelper = $this->helper(\Convert\Catalog\Helper\Data::class);
$bundleHelper = $this->helper('Convert\Catalog\Helper\BundleHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
            __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="top_toolbar">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php
            $a = 0;
            /** @var $_product \Magento\Catalog\Model\Product */
            ?>
            <?php foreach ($_productCollection as $_product):
                $a++;
                ?>
                <?php
                $product = $helper->getLoadProduct($_product->getId());
                // get value attribute
                $datalimit = $product->getData('limited_and_new');
                $dataSale = $product->getData('sale_product');
                // get text attribute
                $attrSale = $product->getResource()->getAttribute('sale_product');
                $attrLimit = $product->getResource()->getAttribute('limited_and_new');
                if ($attrSale->usesSource()) {
                    $valueSale = $attrSale->getSource()->getOptionText($dataSale);
                }

                if ($attrLimit->usesSource()) {
                    $valueLimit = $attrLimit->getSource()->getOptionText($datalimit);
                }

                ?>

                <li class="item product product-item">
                    <div class="list-attribute-product">
                        <?php
                        if (isset($valueLimit)) {
                            ?>
                            <div class="my-attribute attribute-limit-new-<?= $valueLimit ?>">
                                <?= $valueLimit ?>
                            </div>
                            <?php
                        }
                        if (isset($valueSale)) {
                            ?>
                            <div class="my-attribute attribute-sale-product-<?= $valueSale ?>">
                                <?= $valueSale ?>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">

                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image
                        ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <div class="product-name-container">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </div>
                            <div class="product-item-inner">
                                <?php if ($_chelper->isLoggedIn()) : ?>
                                    <div class="product-has-atribute">
                                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                        <?= $block->getProductDetailsHtml($_product) ?>
                                    </div>

                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                      action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <?php $buttonTitle = __('Add to Bag');?>
                                                    <?php if($_product->getTypeId() == 'bundle') : ?>
                                                        <?php if($bundleHelper->checkCanAddToCart($_product)):?>
                                                            <div style="display:block; height: 0; visibility: hidden">
                                                                <?= $bundleHelper->getBundleOptionsHtml($_product); ?>
                                                            </div>
                                                        <?php else: $buttonTitle = __('Select Options') ?>
                                                        <?php endif;?>

                                                    <?php endif;?>
                                                    <div class="control-1">
                                                        <span class="btn-qty btn-qty-minus"></span>
                                                        <input type="number" name="qty" id="qty<?= $a ?>" maxlength="12"
                                                               value="<?php /* @escapeNotVerified */ echo '1' ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"/>
                                                        <button type="submit"
                                                                title="<?= $buttonTitle ?>"
                                                                class="action tocart primary" id="<?= $a ?>">
                                                            <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                                                        </button>
                                                        <span class="btn-qty btn-qty-plus"></span>
                                                    </div>
                                                </form>
                                            <?php else: ?>
                                                
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links"
                                             class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php else : ?>
                                    <div class="user-not-login">
                                        <a href="<?php echo $block->getUrl('customer/account/login'); ?>">Sign In for prices</a>
                                    </div>

                                <?php endif; ?>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                                <strong class="product name product-item-name product-item-name-detail">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */ __('View details') ?>
                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <input type="hidden" id="quantityCt">
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require([
        "jquery",
        "swiper"
    ], function ($, Swiper) {
        jQuery(document).ready(function () {
            /* COMMON FUNCTION ALIGN HEIGHT */
            function alignHeight(selector) {
                jQuery(selector).css('height', '');
                var minHeight = 0;
                jQuery(selector).each(function () {
                    if (minHeight < jQuery(this).outerHeight()) {
                        minHeight = jQuery(this).outerHeight()
                    }
                });
                if (minHeight > 0) {
                    jQuery(selector).css('height', minHeight);
                }
            }

            /* ALIGN HEIGHT PRODUCT NAME PRODUCT GRID */
            setTimeout(function () {
                alignHeight('.page-products .column .products-grid .product-item .product-item-details > .product-name-container ');
            }, 400);
            jQuery(window).resize(function () {
                setTimeout(function () {
                    alignHeight('.page-products .column .products-grid .product-item .product-item-details > .product-name-container');
                }, 400);
            });
            /* ALIGN HEIGHT PRODUCT BRAND GRID */
            setTimeout(function () {
                alignHeight('.page-products .products-grid .product-item .brand');
            }, 400);
            jQuery(window).resize(function () {
                setTimeout(function () {
                    alignHeight('.page-products .products-grid .product-item .brand');
                }, 400);
            });

            /* ALIGN HEIGHT PRODUCT BRAND GRID */
            // setTimeout(function(){
            //   alignHeight('.page-products .products-grid .product-item .product-has-atribute');
            // }, 400);
            // jQuery(window).resize(function() {
            //   setTimeout(function(){
            //     alignHeight('.page-products .products-grid .product-item .product-has-atribute');
            //   }, 400);
            // });

            /* QTY BUTTON ON SITE WIDE */
            $('.control-1 .btn-qty').click(function (e) {
                e.preventDefault();
                var qtyInput = $(this).closest('.control-1').find('input.qty');
                if (!qtyInput.val()) {
                    qtyInput.val(1);
                } else {
                    if ($(this).hasClass('btn-qty-minus')) {
                        var val = parseInt(qtyInput.val());
                        if (val > 1) {
                            qtyInput.val(val - 1);
                            if ($(this).hasClass('cart-qty')) {
                                $('.cart.main.actions .action.update').trigger('click');
                            }
                        }
                    } else {
                        var val = parseInt(qtyInput.val());
                        qtyInput.val(val + 1);
                        if ($(this).hasClass('cart-qty')) {
                            $('.cart.main.actions .action.update').trigger('click');
                        }
                    }
                }
            });
            /* CATEGORY RECENTLY VIEWED SLIDE */
            var load_recently_view = setInterval(function () {
                if (jQuery('.widget.block-viewed-products-grid .product-items').length) {
                    jQuery('.catalog-category-view .page-wrapper .page-main .admin__data-grid-outer-wrap').show();
                    jQuery('.block-products-list').hide();
                    clearInterval(load_recently_view);
                } else {
                    jQuery('.catalog-category-view .page-wrapper .page-main .admin__data-grid-outer-wrap').hide();
                }
            }, 500);
        });

        $(".action.tocart.primary").click(function () {
            var a = $(this).attr("id");
            var numberProduct = $("#qty" + a).val();
            $("#quantityCt").val(numberProduct);
        });
    })
</script>