<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<br />
<table class="shipment-track">
    <thead>
        <tr>
            <th style="font-size: 13px;font-weight: bold;color: #222222;padding-left:0px;padding-bottom:0px;background:#fff;"><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th style="font-size: 13px;font-weight: bold;color: #222222;padding-left:0px;padding-bottom:0px;background:#fff;"><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_shipment->getAllTracks() as $_item): ?>
        <tr>
            <td style="padding-left:0px;background:#fff;"><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
            <td style="padding-left:0px;background:#fff;"><?= $block->escapeHtml($_item->getNumber()) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
