<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getOrder() ?>

<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildrenItems()); ?>

<?php if ($block->getItemOptions() || $_item->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $_item) && $_item->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr class="bundle-option-label">
                <td colspan="6" style="padding-left:10px;">
                    <strong><em><?= /* @escapeNotVerified */  $attributes['option_label'] ?></em></strong>
                </td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!$_item->getParentItem()): ?>
		<?php
			$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
			if($childProd = current($_item->getChildrenItems()))
			{
					$productImage = $_imagehelper->init($childProd->getProduct(), 'category_page_list', array('height' => 83 , 'width'=> 83))->getUrl();
			}
			else
			{
					$productImage = $_imagehelper->init($_item->getProduct(), 'category_page_list', array('height' => 83 , 'width'=> 83))->getUrl();
			}
            $pos = strpos($productImage, 'placeholder');
            if($pos !== false)
            {
                $helper = $this->helper('Convert\Catalog\Helper\Data');
                $productImage = $helper->getEmailProductImage($_item->getProductId()); 
            }
		?>
        <tr class="bundle-item bundle-parent">
			<td>
				<img width="83" style="width:83px;" src="<?=$productImage?>" title="<?= $block->escapeHtml($_item->getName()) ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>" />
			</td>
            <td class="item-info">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
			</td>
			<td>
                <p class="sku"><?= $block->escapeHtml($block->getSku($_item)) ?></p>
            </td>
			<td>
				<?php  
					$price = strip_tags($block->getItemPrice($_item));
					$price = explode('$',$price);
					$price1 = (real) $price[1];
					$qty = (int) $_item->getQtyOrdered();
					$total = number_format($price1/$qty,2);
					echo $price[0].'$'.$total;
				?>
			</td>
            <td class="item-qty">
                <?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?>
            </td>
            <td class="item-price">
                <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
            </td>
        </tr>
    <?php else: ?>
        <tr class="bundle-item bundle-option-value">
            <td class="item-info" colspan="6" style="padding-left:10px;">
                <p><?= $block->getValueHtml($_item) ?></p>
            </td>
        </tr>
    <?php endif; ?>

<?php endforeach; ?>
<tr><td colspan="6" style="border-bottom:solid 1px #eee"> </td></tr>
<?php if ($_showlastRow): ?>
    <tr>
        <td colspan="6" class="item-extra">
            <?php if ($block->getItemOptions()): ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                            <dd><?= /* @escapeNotVerified */  $option['value'] ?></dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
            <?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
                <table class="message-gift">
                    <tr>
                        <td>
                            <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                            <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                            <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                        </td>
                    </tr>
                </table>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
