<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$helper = $this->helper('Convert\Catalog\Helper\Data');
// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
	<?php
	$type = 'widget-product-grid';

	$mode = 'grid';

	$image = 'new_products_content_widget_grid';
	$items = $block->getProductCollection()->getItems();

	$showWishlist = false;
	$showCompare = false;
	$showCart = true;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$description = false;
	?>
    <div class="block widget block-products-list <?= /* @noEscape */
	$mode ?>">
		<?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
		<?php endif ?>
        <div class="block-content">
			<?= /* @noEscape */
			'<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */
			$mode ?> <?= /* @noEscape */
			$mode ?>">
                <ol class="owl-carousel product-items <?= /* @noEscape */
				$type ?>">
					<?php $iterator = 1; ?>
					<?php foreach ($items as $_item): ?>

						<?= /* @noEscape */
						($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
						<?php
						$product = $helper->getLoadProduct($_item->getId());
						// get value attribute
						$datalimit = $product->getData('limited_and_new');
						$dataSale = $product->getData('sale_product');
						// get text attribute
						$attrSale = $product->getResource()->getAttribute('sale_product');
						$attrLimit = $product->getResource()->getAttribute('limited_and_new');
						if ($attrSale->usesSource()) {
							$valueSale = $attrSale->getSource()->getOptionText($dataSale);
						}

						if ($attrLimit->usesSource()) {
							$valueLimit = $attrLimit->getSource()->getOptionText($datalimit);
						}

						?>
                        <div class="list-attribute-product">
							<?php
							if (isset($valueLimit) && $valueLimit == "Limited") {
								?>

                                <div class="my-attribute attribute-limit-new-<?= strtoupper($valueLimit) ?>">
									<?= $valueLimit ?>
                                </div>
								<?php
							}
							if (isset($valueSale)) {
								?>
                                <div class="my-attribute attribute-sale-product-<?= $valueSale ?>">
									<?= $valueSale ?>
                                </div>
								<?php
							}
							?>
                        </div>
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-photo">
								<?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <div class="align-attribute-new">
									<?php
									if (isset($valueLimit) && $valueLimit == "New") {
										?>
                                        <div class="my-attribute attribute-limit-new-<?= strtoupper($valueLimit) ?>">
											<?= $valueLimit ?>
                                        </div>
										<?php
									}
									?>
                                </div>
                                <div class="align-summary">
		                            <span class="stamped-product-reviews-badge" data-id="<?php echo $_item->getId() ?>"
                                          style="display: block;"></span>
                                </div>
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
										<?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
								<?php
								echo $block->getProductPriceHtml($_item, $type);
								?>
                                <div class="align-swatch">
									<?php if ($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
										$swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
										echo $swatchBlock->setProduct($_item)->toHtml();
									} ?></div>
								<?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
										<?php if ($showCart): ?>
                                            <div class="actions-primary">
												<?php if ($_item->isSaleable()): ?>
													<?php /*if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else:*/ ?>
													<?php
													$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
													$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
													?>
                                                    <button class="action tocart primary" data-post='<?= /* @noEscape */
													$postData ?>' type="button"
                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
													<?php //endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span></div>
													<?php else: ?>
                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
													<?php endif; ?>
												<?php endif; ?>
                                            </div>
										<?php endif; ?>
										<?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */
													   $block->getAddToWishlistParams($_item) ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
												<?php endif; ?>
												<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */
													$compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
												<?php endif; ?>
                                            </div>
										<?php endif; ?>
                                    </div>
								<?php endif; ?>
                                <div class="view-details">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"> View details</a>
                                </div>
                            </div>
                        </div>
						<?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
					<?php endforeach ?>
                </ol>
            </div>
			<?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    require([
        'jquery',
        'owlCarousel'
    ], function ($) {
        var width = jQuery(window).width();
        var owl = jQuery('.block-content ol.owl-carousel');

        owl.owlCarousel({
            loop: false,
            dots: true,
            margin: 16,
            nav: true,
            responsiveClass: true,
            // responsive: {
            //     0: {
            //         items: 1,
            //         stagePadding: 74,
            //         autoWidth: true,
            //         loop: false
            //     },
            //     768: {
            //         items: 3,
            //         loop: false
            //     },
            //     1000: {
            //         items: 4,
            //         loop: false
            //     }
            // }


            responsive: {
                0: {
                    items: 1,
                    margin: 16,
                    loop: true,
                    stagePadding: 74
                },
                425: {
                    items: 2,
                    margin: 16,
                    loop: true,
                    stagePadding: 74
                },
                768: {
                    items: 3,
                    margin: 16,
                },
                1024: {
                    items: 4,
                    margin: 24
                }
            }
        });
    });
</script>