<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->getTypeId() == "simple" && !$_product->getSubscriptionEnabled()): ?>
    <div class="product-options-bottom">
<?php endif ?>
<?php if(!$_product->getSubscriptionEnabled()) : ?>
    <ul class="tabs not--subscription">
        <li class="tab-link active" data-tab="tab-1"><p><?= __('One time order') ?></p></li>
    </ul>
    <div id="tab-1" class="tab-content current"></div>
<?php endif ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                <div class="control">
                    <button type="button" id="<?= /* @escapeNotVerified */
                        $_product->getId() ?>-upt" class="decreaseQty"></button>
                    <input type="number"
                           name="qty"
                           id="qty"
                           value=""
                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                           class="input-text qty"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                    <button type="button" id="<?= /* @escapeNotVerified */
                        $_product->getId() ?>-dec" class="increaseQty"></button>
                </div>
            </div>
            <?php endif; ?>
            <?= $block->getChildHtml('product.info.price', true) ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                
            </div>
        </fieldset>
    </div>

    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
    <script type="text/javascript">
        require([
            'jquery'
        ], function (jQuery) {
            (function ($) {

                $(document).ready(function () {

                    $('.box-tocart.update .increaseQty, .box-tocart.update .decreaseQty').click(function () {
                        var $this = $(this);
                        var currentQty = parseInt($("#qty").val());
                        if ($this.hasClass('increaseQty')) {
                            var newAdd = parseInt(currentQty) + parseInt(1);
                            $("#qty").val(newAdd);
                            $("#myaddcart").val(newAdd);
                        } else {
                            if (currentQty > 1) {
                                var newAdd = parseInt(currentQty) - parseInt(1);
                                $("#qty").val(newAdd);
                                $("#myaddcart").val(newAdd);
                            }
                        }
                    });
                    $('ul.tabs li').click(function () {
                        var tab_id = $(this).attr('data-tab');

                        $('ul.tabs li').removeClass('active');
                        $('.tab-content').removeClass('current');

                        $(this).addClass('active');
                        $("#" + tab_id).addClass('current');
                    })
                });
            })(jQuery);
        });
    </script>
<?php endif; ?>
<?php if ($_product->getTypeId() == "simple" && !$_product->getSubscriptionEnabled()): ?>
    </div>
<?php endif ?>