<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Multiselect */
?>
<?php
$fieldCssClass = 'field field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?= /* @escapeNotVerified */ $fieldCssClass ?>">
    <label class="label" for="<?= $block->getHtmlId() ?>"><span><?= /* @escapeNotVerified */ $block->getLabel() ?></span></label>
    <div class="control">
        <?php foreach ($block->getOptions() as $option):?>
            <?php if($option['value'] != ''):?>
                <input type="checkbox" name="<?= $block->getFieldName('') ?>" class="checkbox" id="<?= /* @escapeNotVerified */ $option['value'] ?>" value="<?= /* @escapeNotVerified */ $option['value'] ?>" <?php if ($block->isValueSelected($option['value'])):?> checked <?php endif;?>>
                <label for="<?= /* @escapeNotVerified */ $option['value'] ?>" class="label label_child"><span><?= $block->escapeHtml($option['label']) ?></span></label>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
        <div class="note"><?= /* @escapeNotVerified */ $_message ?></div>
        <?php endif; ?>
    </div>
</div>
