<?php
if ($block->checkconfig() == 1) {
	?>
	<div class="divider free-ship-block">
		<?php
		$currencysymbol = $block->getCurrentCurrencySymbol();  
		$amout_shipping = $block->getAmountFreeship(); 
		$grantotall = $block->getGrandTotal();
		if ($grantotall < $amout_shipping) {
			$amount = $amout_shipping - $grantotall;
			echo "<span>You are <b>".$currencysymbol.$amount."</b> away from <b>free shipping</b></span>";
		}else{
			echo "<span>You qualify for <b>free shipping</b> !</span>";
		}
		?>

	</div>
	<div class="reset"></div>
	<?php
}
else{
	?>
	<div class="none-ship"></div>
	<?php
} 
?>