<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if($block->customerLoggedIn()): ?>
    <li class="customer-welcome">
        <a class="account-link" href="<?php echo $this->getBaseUrl().'customer/account';?>">Account</a>
    </li>
<?php endif; ?>
    