<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?> 
<dl class="payment-method">
    <dt class="title" style="font-weight:400;"><?= /* @noEscape */ $title ?></dt>
<?php if ($specificInfo):?>
    <dd class="content" style="margin-left:0px;">
        <table class="data table">
            <?php foreach ($specificInfo as $label => $value):?>
                <tr>
                    <th scope="row" style="font-weight:400;padding-right:10px;text-align:left;font-size:13px;color:#444444;"><?= $block->escapeHtml($label) ?></th>
                    <td>
                        <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </dd>
<?php endif;?>
</dl>
<?= $block->getChildHtml() ?>
