<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Reports
 */
?>
<?php
/** @var \Amasty\Reports\Block\Adminhtml\Report\Customers\Abandoned\Information $block */
?>
<p class="reklama"><?= __(
    'Do you want to turn lost purchases into completed orders? Send catchy reminders with discount coupons
 to your customers using <a href="%1" target="_blank">Amasty Abandoned Cart Email</a> extension',
    'https://amasty.com/abandoned-cart-email-for-magento-2.html?utm_source=extension&utm_medium=link&utm_campaign=reports-to-abandoned-cart'
    ) ?></p>
