<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<?php
/** @var $block \Amasty\Cart\Block\Product */
$product = $this->getProduct();
$name = $block->escapeHtml($product->getName());

?>
<div class="ajax-added-item">

    <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"
       title="<?= $name; ?>"
       class="added-item">
        <span id="myquantityupdate"></span><span id="myquantity"></span> x <?= $name; ?>
    </a>
    <p class="text"><?= __('has been added to your cart') ?></p>
    <p class="text update"><?= __('has been updated to your cart') ?></p>
    <?php echo $this->getSubscriptionOption() ?>
</div>
<div class="am-photo-container">
    <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"
       title="<?= $name; ?>"
       tabindex="-1"
       class="product-item-photo">
		<?= $block->getImage($product, 'cart_page_product_thumbnail')->toHtml(); ?>
    </a>
	<?= $this->getQtyHtml(); ?>
</div>

<script type="text/javascript">
    require([
        'jquery',
    ], function ($) {
        var checkWeb = $("body").hasClass("catalog-product-view");
        var checkWeb3 = $("body").hasClass("page-multiple-wishlist");
        if (checkWeb == true) {
            var checkbutton = $("#checkbutton").val();
            if (checkbutton == 9) {
                var myquantity = $("#myaddcart").val();
                if (myquantity == "" || myquantity == null) {
                    var quantityProduct = $("#qty").val();
                    $("#myquantity").html(quantityProduct);
                } else {
                    $("#myquantity").html(myquantity);
                }
                $("#checkbutton").val(0);
            } else {
                $("#myquantity").html(1);
            }
        } else if (checkWeb3 == true) {
            var number = $(".quantity_wishlist").val();
            jQuery("#myquantity").html(number);
        } else {
            $("#myquantity").html(1);
        }
    });
</script>
