<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */

$curentcategoryname = '';
$helper = $this->helper('Convert\Catalog\Helper\Data');
$blockcategory = $this->getLayout()->createBlock('Convert\Catalog\Block\Product');
$curentcategory = $blockcategory->getCurrentCategory();
if ($curentcategory) {
$curentcategoryname = strtolower($curentcategory->getName());
}

?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
		<?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */
		$filtered ?>">
            <strong data-role="title"><?= /* @escapeNotVerified */
				__('Filter by concern') ?></strong>
        </div>
        <div class="block-content filter-content">
            <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */
			$filtered ?>">
                <strong data-role="title"><?= /* @escapeNotVerified */
					__('Filter by concern') ?></strong>
            </div>
            <div class="filter-content-area">
				<?php
				if ($block->getChildHtml('state')) : ?>
                <div class="filter-content-top">
					<?php endif; ?>

					<?= $block->getChildHtml('state') ?>

					<?php if ($block->getLayer()->getState()->getFilters()): ?>
                        <div class="block-actions filter-actions">
                            <a href="<?= /* @escapeNotVerified */
							$block->getClearUrl() ?>"
                               class="action clear filter-clear"><span><?= /* @escapeNotVerified */
									__('Clear All') ?></span></a>
                        </div>
					<?php endif; ?>
					<?php if ($block->getChildHtml('state')) : ?>
                </div>
			<?php endif; ?>
				<?php $wrapOptions = false; ?>
				<?php foreach ($block->getFilters() as $filter): ?>
			<?php if ($filter->getItemsCount()): ?>
			<?php if (!$wrapOptions): ?>

                <strong role="heading" aria-level="2"
                        class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */
					__('Shopping Options') ?></strong>
                <div class="filter-options" id="narrow-by-list" data-role="content"
                     data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
					<?php $wrapOptions = true;
					endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
						<?php
						if ($filter->getName() != 'Category') : 
							?>
                            <div data-role="title" class="filter-options-title">Filter by <?= /* @escapeNotVerified */
								__(strtolower($filter->getName())) ?></div>
                            <div data-role="content" class="filter-options-content checked"><?= /* @escapeNotVerified */
								$block->getChildBlock('renderer')->render($filter) ?></div>
						<?php endif; ?>
                    </div>
					<?php endif; ?>
					<?php endforeach; ?>
					<?php if ($wrapOptions): ?>
                </div>
			<?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
				<?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
