<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<?php
/** @var $block \Amasty\Cart\Block\Product */
$product = $this->getProduct();
$name = $block->escapeHtml($product->getName());

?>
<div class="ajax-added-item">

    <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"
       title="<?= $name; ?>"
       class="added-item">
        <span id="myquantity"></span> x <?= $name; ?>
    </a>
    <p class="text"><?= __('has been added to your cart') ?></p>
</div>
<div class="am-photo-container">
    <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"
       title="<?= $name; ?>"
       tabindex="-1"
       class="product-item-photo">
		<?= $block->getImage($product, 'cart_page_product_thumbnail')->toHtml(); ?>
    </a>
	<?= $this->getQtyHtml(); ?>
</div>

<script type="text/javascript">
    require([
        'jquery',
    ], function ($) {

        var checkWeb1 = jQuery("body").hasClass("cms-index-index");
        var checkWeb2 = jQuery("body").hasClass("catalog-product-view");
        var checkWeb3 = jQuery("body").hasClass("page-multiple-wishlist");
        var checkWeb4 = jQuery("body").hasClass("cvquickorder-index-index");
        if (checkWeb1 == true) {
            var numberProduct = jQuery("#quantityhome").val();
            jQuery("#myquantity").html(numberProduct);
            jQuery("#am-input").val(numberProduct);
            jQuery('#am-input').trigger("chosen:updated");
        } else if (checkWeb2 == true) {
            var numberProductDetail = jQuery("#myaddcart1").val();
            var checkbutton = $("#checkbutton").val();
            if (checkbutton == 9) {
                if (numberProductDetail != "" && numberProductDetail != null) {
                    jQuery("#myquantity").html(numberProductDetail);
                    jQuery("#am-input").val(numberProductDetail);
                    jQuery('#am-input').trigger("chosen:updated");
                } else {
                    jQuery("#myquantity").html(1);
                    jQuery("#am-input").val(1);
                    jQuery('#am-input').trigger("chosen:updated");
                }
                $("#checkbutton").val(0);
            } else {
                $("#myquantity").html(1);
            }
        } else if (checkWeb3 == true) {
            var number = $("#quantity_wishlist").val();
            jQuery("#myquantity").html(number);
        } else if (checkWeb4 == true) {
            var number = $("#quantityCt").val();
            jQuery("#myquantity").html(number);
        } else {
            var numberProductCt = jQuery("#quantityCt").val();
            jQuery("#myquantity").html(numberProductCt);
            jQuery("#am-input").val(numberProductCt);
            jQuery('#am-input').trigger("chosen:updated");
        }

    });
</script>
