<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order    = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
	<table style="width:100%;">
		<tr><td style="width:100%;height:30px;border-top:solid 1px #eee;"></td></tr>
	</table>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info" style="padding-top:10px !important;padding-bottom:10px !important; padding-left:20px !important; width:39% !important;font-size:13px; color:#222222; font-weight:bold; background-color:#f2f2f2; text-transform: capitalize;">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
				<th class="item-info" style="padding-top:10px !important;padding-bottom:10px !important; width:39% !important;font-size:13px; color:#222222; font-weight:bold; background-color:#f2f2f2; text-transform: capitalize;">
                    <?= /* @escapeNotVerified */  __('Sku'); ?>
                </th>
                <th class="item-qty" style="padding-top:10px !important;padding-bottom:10px !important;width:41.5%; text-align:center;font-size:13px; color:#222222; font-weight:bold;background-color:#f2f2f2;padding-right:20px !important;text-transform: capitalize;">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_shipment->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
