<a href="<?= $block->getBaseUrl() . 'contact'; ?>" id="ask-question" title="Ask question" class="ask-question" ><span><?= __('Ask a question') ?></span></a>
<!--<script>
    require(['jquery'], function ($) {
        $('#ask-question').click(function (e) {
            e.preventDefault();
            $("body, html").animate({
                scrollTop: $('.stamped-summary-actions-newquestion').offset().top
            }, 500);
        });
    });
</script>-->
