<?php
$blockCategory = $block->getLayout()->createBlock('Convert\CategoryThumbnail\Block\HomeFavorites');
$cat_id = $this->getData('category_id');
$_category = $blockCategory->getCategoryFavorites($cat_id);
$subcats = $_category->getChildrenCategories();
$objectHelper = $this->Helper('Convert\CategoryThumbnail\Helper\Data');
$mediaUrl = $objectHelper->getMediaUrl();
$count = count($subcats);
$categoryShop = $objectHelper->getLoadCategory($cat_id);
$linktoshopcate = $categoryShop->getUrl();
?>


<!--Set name category Shop all link to category shop-->
<div class="mega-category-with-thumbnail shopall">
        <div class="item">
        <?php if ($categoryShop->getCategoryThumbnail()): ?>
            <a class="cat_img" href="<?php echo $linktoshopcate ?>">
                <img src="<?php echo $categoryShop->getCategoryThumbnail() ?>"
                title="<?= __('Shop All')  ?>"/>
            </a>
            <?php else: ?>
                <a class="cat_img" href="<?php echo $linktoshopcate ?>">
                    <img src="<?php echo $mediaUrl . 'default_thumbnail.jpg' ?>"
                    title="<?= __('Shop All') ?>"/>
                </a>
            <?php endif; ?>
        </div>
        <div class="content">
            <div class="text">
                <a class="cat_name" href="<?= $linktoshopcate ?>"><?= __("Shop All") ?></a>
            </div>
        </div>
    </div>
    <!-- End -->

<?php foreach ($subcats as $subcat): ?>
	<?php

    $categoryName = $subcat->getName();
    $category = $objectHelper->getLoadCategory($subcat->getId());
    if (strpos($category->getUrl(), 'shop/e-gift-card') !== false) {
        $link = str_replace('shop/e-gift-card', 'shop/e-gift-card/gift-card-online', $category->getUrl());
    } else {
        $link = $category->getUrl();
    }
    if($category->getIncludeInMenu()):
        // if ($categoryName == "Shop All") {
        // 	$a = "shopall";
        // 	$link = $block->getBaseUrl() . "shop";
        // } else {
        // 	$a = "";
        // }
        ?>
        <div class="mega-category-with-thumbnail ">
            <div class="item">

                <?php if ($category->getCategoryThumbnail()): ?>
                    <a class="cat_img" href="<?php echo $link ?>">
                        <img src="<?php echo $category->getCategoryThumbnail() ?>"
                             title="<?php echo $categoryName; ?>"/>
                    </a>
                <?php else: ?>
                    <a class="cat_img" href="<?php echo $link ?>">
                        <img src="<?php echo $mediaUrl . 'default_thumbnail.jpg' ?>"
                             title="<?php echo $categoryName; ?>"/>
                    </a>
                <?php endif; ?>
            </div>
            <div class="content">
                <div class="text">
                    <a class="cat_name" href="<?php echo $link ?>"><?php echo $categoryName; ?></a>
                </div>
            </div>
        </div>
    <?php endif;?>
<?php endforeach; ?>


