<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php $helper = $this->helper('Convert\Catalog\Helper\Data'); ?>
<?php if($helper->isCustomerLoggedIn()): ?>
  <div class="product-addto-links" data-role="add-to-links">
      <?= $block->getChildHtml() ?>
  </div>
<?php endif; ?>
