<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>

<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
$_isCmsBlock = $block->getIsCmsBlock();
$_iconAttributeCode = $block->getIconCode();
$_helper2 = $this->helper('Convert\Catalog\Helper\Data');
//$cHelper = $this->helper(\Amasty\ShopbyBase\Helper\OptionSetting::class);
$mediaUrl = $_helper2->getMediaUrl();
if (substr($mediaUrl, -1) !== '/') {
	$mediaUrl = $mediaUrl . '/';
}

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
	$renderLabel = false;
}
if ($_isCmsBlock) {
	$_attributeValue = $block->getCmsBlockCode();
} else {
	if ($_attributeLabel && $_attributeLabel == 'default') {
		$_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
	}
	if ($_attributeType && $_attributeType == 'text') {
		$_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
	} else {
		$_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
	}
}
?>

<?php if ($_attributeValue): ?>
    <div class="product attribute <?= /* @escapeNotVerified */
	$_className ?>">
		<?php if ($renderLabel): ?><strong class="type"><?= /* @escapeNotVerified */
		$_attributeLabel ?></strong><?php endif; ?>
        <div class="value" <?php if ('overview' != $_className) {
			echo $_attributeAddAttribute;
		} ?>>
			<?php if ($_isCmsBlock): ?>
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($_attributeValue)->toHtml(); ?>
			<?php else: ?>
				<?php if ('overview' == $_className): ?>
					<?php
					$shortDesc = $_attributeValue;
					if (strlen($_attributeValue) > 240) {
						$shortDesc = substr(strip_tags($_attributeValue), 0, 240) . '...';
					}
					?>
                     <div class="short-desc-icon-wrapper">
                       <!-- <div class="sub-short-desc">
                            <div><?php /*echo $shortDesc; */?></div>
                            <a href="#" class="readmore-short-desc"><?php /*echo __('Read more') */?></a>
                        </div>
                        <div class="full-short-desc" <?php /*echo $_attributeAddAttribute; */?> style="display: none;">
							<?php /*echo $_attributeValue; */?>
                            <a href="#" class="readless-full-desc"><?php /*echo __('Read less') */?></a>
                        </div>-->
                         <div class="full-short-descs-attribute" style="height: 150px;overflow: hidden">
                            <?= $_attributeValue ?>
                        </div>
                        <div class="check-short-descs-attribute" style="display: none">
                            <?= $_attributeValue ?>
                        </div>
                       <div class="button-read-bundle">
                         <a href="#" class="readmore-short-descs-attribute"><?php echo __('Read more') ?></a>
                         <a href="#" class="lessmore-short-descs-attribute" style="display: none"><?php echo __('Read less') ?></a>
           </div>
                    </div>
					<?php if ($_product->getData('desc_icon')): ?>
                        <div class="description-icons">
							<?php $data = explode(',', $_product->getData('desc_icon')); ?>
							<?php foreach ($data as $value): ?>
								<?php
								//$setting = $cHelper->getSettingByValue($value, 'attr_desc_icon', $_product->getStoreId());
								$attr = $_product->getResource()->getAttribute('desc_icon');
								?>
								<?php if ($attr->usesSource()): ?>
									<?php
									$option_value = $attr->getSource()->getOptionText($value);
									$optionValue = strtolower($option_value);
									$optionName = str_replace(' ', '-', $optionValue);
									$optionName = str_replace('-&-', '-', $optionName);
									$special_character = array("'",")","(","/");
									$optionName = str_replace($special_character,"",$optionName);
									$className = str_replace(' ', '-', $optionValue);
									$urlImages = $mediaUrl . $optionName . '.png';
									?>
									<?php if ($option_value): ?>
                                        <div class="icon-content">
											<?php /*if ($setting->getImage()): ?>
                                                <img src="<?php echo $setting->getImageUrl() ?>" alt=""
                                                     class="icon-attribute">
											<?php else : ?>
                                                <img src="<?php echo $mediaUrl . '/default_ingredients_icons.png' ?>"
                                                     alt="" class="icon-attribute">
											<?php endif; */ ?>
											<img src="<?php                                                
															echo $mediaUrl . $optionName . '.png'; 
													?>"
                                                     alt=""
                                                     class="icon-attribute">
                                            <p class="attribute-name <?php echo $className; ?>">
                                            <?php 
                                                     	if (strpos($option_value, 'Poni')) 
                                                     	{
                                                     		echo str_replace('Poni','',$option_value);
                                                     	}else if (strpos($option_value, 'Esmi')) 
                                                     	{
                                                     		echo str_replace('Esmi','',$option_value);
                                                     	}else{
                                                     		echo $option_value;

                                                     	}
                                                     	 ?>
                                            </p>
                                        </div>
									<?php endif; ?>
								<?php endif; ?>
							<?php endforeach; ?>
                        </div>
					<?php endif; ?>
				<?php endif; ?>

				<?php if ('overview' != $_className): ?>
					<?= /* @escapeNotVerified */
					$_attributeValue ?>
				<?php endif; ?>
				<?php if ($_iconAttributeCode): ?>
					<?php if ($_product->getData($_iconAttributeCode)):
						if ($_iconAttributeCode == "ingredients_icons") {
							?>
                            <div class="icon-attribute-wrapper <?php echo $_iconAttributeCode; ?>">
								<?php
								$data = explode(',', $_product->getData($_iconAttributeCode));
								foreach ($data as $value):
									//$setting = $cHelper->getSettingByValue($value, "attr_" . $_iconAttributeCode, $_product->getStoreId());
									?>
									<?php $attr = $_product->getResource()->getAttribute($_iconAttributeCode); ?>
									<?php if ($attr->usesSource()): ?>
									<?php
									$option_value = $attr->getSource()->getOptionText($value);
									$optionValue = strtolower($option_value);
									$optionName = str_replace(' ', '-', $optionValue);
									$optionName = str_replace('-&-', '-', $optionName);
									$className = str_replace(' ', '-', $optionValue);
									?>
									<?php if ($option_value): ?>
                                        <div class="icon-content">
											<?php /*if ($setting->getImage()) : ?>
                                                <img src="<?php echo $setting->getImageUrl() ?>" alt=""
                                                     class="icon-attribute">
											<?php else : ?>
                                                <img src="<?php echo $mediaUrl . '/default_ingredients_icons.png' ?>"
                                                     alt=""
                                                     class="icon-attribute">
											<?php endif; */ ?>
											<img src="<?php echo $mediaUrl . $optionName . '.png' ?>"
                                                     alt=""
                                                     class="icon-attribute">
                                            <p class="attribute-name <?php echo $className; ?>"><?php echo $option_value; ?></p>
                                        </div>
									<?php endif; ?>
								<?php endif; ?>
								<?php endforeach; ?>
                            </div>
							<?php
						}
						?>
					<?php endif ?>
				<?php endif; ?>
			<?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<script>
    require([
        'jquery',
        'priceBox'
    ], function ($) {
        $(document).ready(function (event) {

            var checkHeight = $(".check-short-descs-attribute").height();
            if(checkHeight <= 150){
                $(".readmore-short-descs-attribute").addClass("none");
                $(".full-short-descs-attribute").addClass("none")
            }

            $(".readmore-short-descs-attribute").click(function (e) {
                e.preventDefault();
                $(".full-short-descs-attribute").css('height', 'auto');
                $(".lessmore-short-descs-attribute").css('display', 'block');
                $(".readmore-short-descs-attribute").css('display', 'none');
            });

            $(".lessmore-short-descs-attribute").click(function (e) {
                e.preventDefault();
                $(".full-short-descs-attribute").css('height', '150px');
                $(".lessmore-short-descs-attribute").css('display', 'none');
                $(".readmore-short-descs-attribute").css('display', 'block');
            });
        });

    });
</script>
