<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
$curentcategoryname = '';
$helper = $this->helper('Convert\Catalog\Helper\Data');
$blockcategory = $this->getLayout()->createBlock('Convert\Catalog\Block\Product');
$curentcategory = $blockcategory->getCurrentCategory();
if ($curentcategory) {
$curentcategoryname = strtolower($curentcategory->getName());
}
?>

<?php //if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <!-- <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?=
        $filtered ?>">
            <strong data-role="title"><?= __('Filter by') ?></strong>
        </div> -->
        <div class="block-content filter-content">
            <div class="filter-content-area">
                <div class="filter-content-top">
                    <?= $block->getChildHtml('state') ?>

                    <?php if ($block->getLayer()->getState()->getFilters()): ?>
                        <div class="block-actions filter-actions">
                            <a href="<?= /* @escapeNotVerified */
                            $block->getClearUrl() ?>"
                               class="action clear filter-clear"><span><?= /* @escapeNotVerified */
                                    __('Clear All') ?></span></a>
                        </div>
                    <?php endif; ?>

                </div>


                <?php $wrapOptions = false; ?>

                <!--  Filter category   -->
                <div data-role="collapsible" class="filter-options-item">
                    <div data-role="title" class="filter-options-title title-first">
                        <?= /* @escapeNotVerified */__('Lip Heroes range') ?>   
                    </div>
                    <div data-role="content" class="filter-options-content no-check">
                        <ol class="items">

                            <!--Set link shop alll-->
                            <?php if ($curentcategoryname == 'shop all'): ?>
                                <li class="item shop-all active">
                                    <a href="<?= $block->getBaseUrl() . 'shop' ?>"> <?= __('shop all'); ?> </a>
                                </li>
                                <?php else: ?>
                                    <li class="item shop-all">
                                        <a href="<?= $block->getBaseUrl() . 'shop' ?>"> <?= __('shop all'); ?> </a>
                                    </li>
                                <?php endif; ?>

                            <!-- Load subcategory on sidebar-->
                            <?php
                            $listCategory = $helper->getCategoryConvert();
                            if (count($listCategory) > 0) : ?>
                                <?php foreach ($listCategory as $value): ?>
                                    <?php $categorynamefilter = strtolower($value['name']); ?>
                                    <?php if ($curentcategoryname == $categorynamefilter):?>
                                        <li class="item <?php echo $value['url'] ?> active">
                                            <a href="<?= $block->getBaseUrl() . "" . $value['url_parent'] . "/" . $value['url'] ?>"><?= $value['name'] ?></a>
                                        </li>
                                        <?php else: ?>
                                            <li class="item <?php echo $value['url'] ?>">
                                                <a href="<?= $block->getBaseUrl() . "" . $value['url_parent'] . "/" . $value['url'] ?>"><?= $value['name'] ?></a>
                                            </li>
                                        <?php endif; ?>                                   
                                    <?php endforeach; ?>
                                <?php endif; ?>
                                <!-- Load subcategory on sidebar-->

                            </ol>
                        </div>
                </div>
                <!--  End Filter category   -->



                <?php foreach ($block->getFilters() as $filter): ?>
            <?php if ($filter->getItemsCount()): ?>
            <?php if (!$wrapOptions): ?>
                <strong role="heading" aria-level="2"
                        class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */
                    __('Shopping Options') ?></strong>
                <div class="filter-options" id="narrow-by-list" data-role="content"
                     data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    <?php $wrapOptions = true;
                    endif; ?>
                        <?php
                        if ($filter->getName() == 'Category') {
                            ?>

                        <?php } else { ?>
                            <div data-role="collapsible" class="filter-options-item">
                            <div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */
                                __(strtolower($filter->getName())) ?></div>
                            <div data-role="content" class="filter-options-content checked"><?= /* @escapeNotVerified */
                                $block->getChildBlock('renderer')->render($filter) ?></div>
                            </div>
                            <?php
                        }
                        ?>
                    <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php // endif; ?>
