<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_category = $block->getCurrentCategory();
$_imgHtml = '';


if ($_imgUrl = $_category->getImageUrl()) {
	$_imgHtml = '<div class="category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" /></div>';
	$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
	/* @escapeNotVerified */
	echo $_imgHtml;
}

if ($_imgUrl1 = $_category->getCategory_mobile_thumbnail()) {
	$_imgHtml = '<div class="category-image mobile"><img src="' . $_imgUrl1 . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" /></div>';
	$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'category_mobile_thumbnail');
	/* @escapeNotVerified */
	echo $_imgHtml;
}
?>
