<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?= /* @escapeNotVerified */
        $block->getProductUrl() ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else: ?>
            <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= /* @escapeNotVerified */
                    $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php if (!array_key_exists('has_html', $_option)) : ?>
                                    <?php if ($_option['label'] == "Regular Delivery") :  ?>
                                        <?=  $_formatedOptionValue['value'] . " Subscription" ?>
                                    <?php else: ?>
                                        <?php if ($_option['label'] == "Delivery") :  ?>
                                            <?=  $_formatedOptionValue['value'] . " Order" ?>
                                        <?php else: ?>
                                            <?= /* @escapeNotVerified */ $_formatedOptionValue['value']  ?>
                                        <?php endif;?>
                                    <?php endif;?>
                                <?php else: ?>
                                        <?= /* @escapeNotVerified */ $_formatedOptionValue['value']  ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @escapeNotVerified */
                    $message['type'] ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="actions-toolbar edit-cart-item">
                <?= /* @escapeNotVerified */
                $block->getActions($_item) ?>
            </div>
        </div>
    </td>
    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */
                        __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */
                    ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */
                    $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */
                    $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */
                            __("What's this?") ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <label class="label" for="cart-<?= /* @escapeNotVerified */
            $_item->getId() ?>-qty">
                <span><?= /* @escapeNotVerified */
                    __('Qty') ?></span>
            </label>
            <div class="control qty">
                <span class="btn_I_or_D bt-increase">-</span>
                <input id="cart-<?= /* @escapeNotVerified */
                $_item->getId() ?>-qty"
                       name="cart[<?= /* @escapeNotVerified */
                       $_item->getId() ?>][qty]"
                       data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                       value="<?= /* @escapeNotVerified */
                       $block->getQty() ?>"
                       type="number"
                       size="4"
                       title="<?= $block->escapeHtml(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
                <span class="btn_I_or_D bt-decrease">+</span>
            </div>
            <div class="mobile-actions">
              <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            </div>
            <div class="mobile-subtotal">
              <?php if ($canApplyMsrp): ?>
                  <span class="cart msrp subtotal">--</span>
              <?php else: ?>
                  <?= $block->getRowTotalHtml($_item) ?>
              <?php endif; ?>
            </div>
        </div>
        
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>

    <td class="col item-actions">
        <div class="actions-toolbar delete-cart-item">
            <?= /* @escapeNotVerified */
            $block->getActions($_item) ?>
        </div>
    </td>
</tr>
<?php /*$addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
<?php if ($addInfoBlock && $addInfoBlock->setItem($_item)->toHtml() != ''): ?>
    <tr class="additional-info-wrapper">
        <td colspan="100" class="col additional-info">
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <span class="update_product_cart"
                  style="background: #B1526E;color: #FFFFFF;font-size: 15px;padding: 8px 25px;border-radius: 3px;font-weight: bold;cursor: pointer">Update Cart</span>
        </td>
    </tr>
<?php endif;*/ ?>
</tbody>
