<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Paypal\Block\Express\Shortcut $block
 */
?>
<?php
$labelPosition = '';
if ($block->isOrPositionBefore()) {
    $labelPosition = ' before';
} elseif ($block->isOrPositionAfter()) {
    $labelPosition = ' after';
}
$shortcutHtmlId = $block->escapeHtml($block->getShortcutHtmlId());
$isInCatalogProduct = false;
if ($block->getIsInCatalogProduct()) {
    $isInCatalogProduct = $block->getIsInCatalogProduct();
}
$image = $block->escapeUrl($block->getImageUrl());
// $ppimg = $image;
if(strlen($image) == '154') {
    $ppimg = 'https://www.paypalobjects.com/webstatic/en_US/i/buttons/PP_logo_h_100x26.png';
} else {
    $ppimg = $image;
}
?>
<div data-label="<?= $block->escapeHtml(__('or')) ?>"
     class="paypal checkout <?= /* @noEscape */ $labelPosition ?> paypal-logo
        <?= /* @noEscape */ $shortcutHtmlId ?>"
     data-mage-init='{
     "paypalCheckout": {
                "isCatalogProduct": "<?= /* @noEscape */ !empty($isInCatalogProduct) ? (bool)$isInCatalogProduct : false ?>",
                "shortcutContainerClass": "<?= /* @noEscape */ "." . $shortcutHtmlId ?>"
            }
     }'
    >
    <input type="image" data-action="checkout-form-submit"
           data-checkout-url="<?= $block->escapeUrl($block->getCheckoutUrl()) ?>"
           src="<?= $ppimg; ?>"
           alt="<?= $block->escapeHtml(__('Checkout with PayPal')) ?>"
           title="<?= $block->escapeHtml(__('Checkout with PayPal')) ?>"/>
    <?php if ($block->getAdditionalLinkImage()): ?>
        <?php $linkImage = $block->getAdditionalLinkImage(); ?>
        <a href="<?= $block->escapeUrl($linkImage['href']) ?>">
            <img src="<?= $block->escapeHtml($linkImage['src']) ?>" />
        </a>
    <?php endif; ?>
</div>
