<script src="//foursixty.com/media/scripts/fs.embed.v2.5.js" data-feed-id="poni-cosmetics" data-theme="sizes_v2_5" data-page-size="28"></script><style>.fs-has-links

{display:none;}
.fs-wrapper div.fs-text-container .fs-entry-title, div.fs-detail-title

{font-family:Gotham, Light;font-style:italic;font-weight:normal;}
div.fs-text-container .fs-entry-date, div.fs-detail-container .fs-post-info, div.fs-wrapper div.fs-has-links::after, .fs-text-product, .fs-overlink-text

{font-family:Blair, Medium;font-style:normal;font-weight:bold;}
.fs-slider-next-button, .fs-slider-prev-button

{ opacity: 1; }
.fs-wrapper div.fs-text-container *

color: Color value is invalid
.fs-wrapper div.fs-text-container

{background-color:rgba(78, 193, 224, 0); margin: 13px}
div.fs-entry-date

{display:none}
div.fs-service-icon

{display:none}
div.fs-entry-title

{display:none}
.fs-wrapper div.fs-timeline-entry

{ margin: 6px }
</style>


