<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$helper = $this->helper('Convert\Catalog\Helper\Data');

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

use Magento\Framework\App\Action\Action;

?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="owl-carousel product-items <?= /* @noEscape */ $type ?>">
                    <?php
                    $iterator = 1;
                    $a = 0;
                    ?>
                    <?php
                    foreach ($items as $_item):
                        $a++;

                        ?>

                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <?php
                            $product = $helper->getLoadProduct($_item->getId());
                            // get value attribute
                            $datalimit = $product->getData('limited_and_new');
                            $dataSale = $product->getData('sale_product');
                            // get text attribute
                            $attrSale = $product->getResource()->getAttribute('sale_product');
                            $attrLimit = $product->getResource()->getAttribute('limited_and_new');
                            if ($attrSale->usesSource()) {
                                $valueSale = $attrSale->getSource()->getOptionText($dataSale);
                            }

                            if ($attrLimit->usesSource()) {
                                $valueLimit = $attrLimit->getSource()->getOptionText($datalimit);
                            }

                            ?>
                            <div class="list-attribute-product">
                                <?php
                                if (isset($valueLimit)) {
                                    ?>

                                    <div class="my-attribute attribute-limit-new-<?= $valueLimit ?>">
                                        <?= $valueLimit ?>
                                    </div>
                                    <?php
                                }
                                if (isset($valueSale)) {
                                    ?>
                                    <div class="my-attribute attribute-sale-product-<?= $valueSale ?>">
                                        <?= $valueSale ?>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <div class="align-summary">
                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>
                                </div>
                                <span class="brand"><?php
                                    $attribute_code = 'brand';
                                    echo $_item->getResource()->getAttribute($attribute_code)->getFrontend()->getValue($_item);
                                    ?>
                                </span>
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php
                                                    $blockListProduct = $this->getLayout()->createBlock(\Magento\Catalog\Block\Product\ListProduct::class);
                                                    $postParams = $blockListProduct->getAddToCartPostParams($_item);
                                                    ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add') . 'uenc/' . $postParams['data'][Action::PARAM_NAME_URL_ENCODED] . '/product/' . $postParams['data']['product'] ?>"
                                                          method="post">
                                                        <input type="hidden" name="product"
                                                               value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                               value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?php echo $block->getBlockHtml('formkey') ?>
                                                        <div class="align-swatch">
                                                            <?php if ($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
                                                                $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                                                echo $swatchBlock->setProduct($_item)->toHtml();
                                                            } ?></div>

                                                        <div class="field qty">
                                                            <div class="control">
                                                                <span class="minus-btn qty-btn"></span>
                                                                <input type="number"
                                                                       name="qty"
                                                                       id="homeproduct<?= $a ?>"
                                                                       maxlength="12"
                                                                       value="1"
                                                                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>"
                                                                       class="input-text qty"
                                                                />
                                                                <span class="plus-btn qty-btn"></span>
                                                            </div>
                                                        </div>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to cart')); ?>"
                                                                class="action tocart primary"
                                                                id="<?= $a ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else: ?>

                                                        <div class="align-swatch">
                                                            <?php if ($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
                                                                $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                                                echo $swatchBlock->setProduct($_item)->toHtml();
                                                            } ?></div>

                                                        <div class="field qty">
                                                            <div class="control">
                                                                <span class="minus-btn qty-btn"></span>
                                                                <input type="number"
                                                                       name="qty"
                                                                       id="homeproduct<?= $a ?>"
                                                                       maxlength="12"
                                                                       value="1"
                                                                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>"
                                                                       class="input-text qty"
                                                                />
                                                                <span class="plus-btn qty-btn"></span>
                                                            </div>
                                                        </div>


                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <div class="user-not-login">
                                    <a href="<?php echo $block->getUrl('customer/account/login'); ?>">Sign In for prices</a>
                                </div>
                                <div class="view-details">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"> View details</a>
                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <input type="hidden" id="quantityPdHome" value="<?= $a ?>">
    <input type="hidden" id="quantityhome">
<?php endif; ?>
<script type="text/javascript">
    require([
        'jquery',
        'owlCarousel'
    ], function ($) {
        if (window.isLoggedIn) {
            $('.product-item-actions').show();
            $('.user-not-login').hide()
        } else {
            $('.product-item-actions').hide();
            $('.user-not-login').show()
        }
        function alignHeightDocument() {
            var maxHeightName = 0;
            var maxHeightName1 = 0;
            var maxHeightName2 = 0;

            $('.product-item-name').each(function () {
                if (parseFloat($(this).height()) > maxHeightName) {
                    maxHeightName = $(this).height();
                }
            })
            if (maxHeightName > 0) {
                $('.product-item-name').css('height', maxHeightName);
            }

            $('.brand').each(function () {
                if (parseFloat($(this).height()) > maxHeightName1) {
                    maxHeightName1 = $(this).height();
                }
            })
            if (maxHeightName1 > 0) {
                $('.brand').css('height', maxHeightName1);
            }
            setInterval(function () {
                $('.align-swatch').each(function () {
                    if (parseFloat($(this).height()) > maxHeightName2) {
                        maxHeightName2 = $(this).height();
                    }
                })
                if (maxHeightName2 > 0) {
                    $('.align-swatch').css('height', maxHeightName2);
                }
            }, 3000);
        }

        var width = jQuery(window).width();
        var owl = jQuery('.block-content ol.owl-carousel');

        owl.on('initialized.owl.carousel', function () {
            $(window).on('load', function () {
                $(window).resize(function () {
                    alignHeightDocument();
                });
                alignHeightDocument();
            });
        });
        owl.owlCarousel({
            dots: true,
            nav: true,
            loop: false,
            navText: ["<img src='<?php echo $block->getViewFileUrl('images/owl_prev.png') ?>'>", "<img src='<?php echo $block->getViewFileUrl('images/owl_next_mc.png')?>'>"],
            responsive: {
                0: {
                    items: 1,
                    margin: 16,
                    loop: true,
                    stagePadding: 74
                },
                414: {
                    items: 2,
                    margin: 24
                },
                768: {
                    items: 3,
                    margin: 24
                },
                1024: {
                    items: 4,
                    margin: 24
                }
            }
        });
        $(document).click(function (e) {
            var t = $(e.target),
                pQ = t.closest('.product-item-actions .plus-btn'),
                mQ = t.closest('.product-item-actions .minus-btn');
            if (pQ.length) {
                var input = pQ.parent().find('input[name="qty"]'),
                    oldQty = input.val(),
                    newQty = parseInt(oldQty) + 1;
                input.val(newQty);
            }
            if (mQ.length) {
                var input = mQ.parent().find('input[name="qty"]'),
                    oldQty = input.val(),
                    newQty = parseInt(oldQty) - 1;
                if (newQty > 0) {
                    input.val(newQty);
                }
            }
        });

        $(".action.tocart.primary").click(function () {
            var a = $(this).attr("id");
            var numberProduct = $("#homeproduct" + a).val();
            $("#quantityhome").val(numberProduct);
        });


    });

</script>