<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

use Magento\Store\Model\BaseUrlChecker;

/* @var $block \Aheadworks\Blog\Block\Sidebar\Recent */

// @codingStandardsIgnoreFile
?>
<?php
$categorys = $this->helper('Convert\Blog\Helper\Data');
$categories = $categorys->getCategories();
$displayLimit = $block->getNumCategoriesToDisplay();
$indexItem = 0;

$blockObj = $block->getLayout()->createBlock('Aheadworks\Blog\Block\Widget\TagCloud');

$tagCloudItems = $blockObj->getItems();

?>
<?php if (count($categories)): ?>
    <div id="blog_image_sidebar">
        <div id="blog-sidebar-category-listing" class="block widget blog-sidebar-block">
            <div class="block-title">
                <h1 class="blog-my-title">
					<?php echo __("Blog") ?>
                </h1>
                <strong class="blog-sidebar-block-title"><?php echo $block->escapeHtml(__('CATEGORIES')) ?></strong>
            </div>

            <div class="block-content blog-sidebar-block-content">
                <span class="toggle-menu-responsive" id="BLOG_NAVIGATION">BLOG NAVIGATION</span>
                <ul data-mage-init='{"awBlogToggleCategories":{}}' class="block-category-listing category"
                    id="blog_navigation">
                    <strong class="blog-sidebar-block-title-responsive"><?php echo $block->escapeHtml(__('CATEGORIES')) ?></strong>
					<?php foreach ($categories as $category): ?>
						<?php $indexItem++; ?>
                        <li class="block-category-listing-item <?php /* @noEscape */
						echo $block->getAdditionalClass($indexItem) ?>">
                            <a href="<?php /* @noEscape */
							echo $block->escapeXssInUrl($block->getCategoryUrl($category)) ?>"
                               class="block-category-listing-item-link">
								<?php echo $block->escapeHtml($category->getName()) ?>
                            </a>
                        </li>
					<?php endforeach; ?>
                </ul>
				<?php
				if ($blockObj->isEnabled() && count($tagCloudItems)) {
					?>
                    <ul data-mage-init='{"awBlogToggleCategories":{}}' class="block-category-listing responsive">
                        <strong class="blog-sidebar-block-title-responsive"><?php echo $block->escapeHtml(__('TAGS')) ?></strong>
						<?php foreach ($tagCloudItems as $tagCloudItem): ?>
							<?php $indexItem++; ?>
                            <li class="block-category-listing-item <?php /* @noEscape */
							echo $block->getAdditionalClass($indexItem) ?>">
                                <a href="<?php /* @noEscape */
								echo $blockObj->escapeXssInUrl($blockObj->getSearchByTagUrl($tagCloudItem)) ?>"
                                   class="block-category-listing-item-link">
									<?php echo $blockObj->escapeHtml($tagCloudItem->getTag()->getName()) ?>
                                </a>
                            </li>
						<?php endforeach; ?>
                    </ul>
					<?php
				}
				?>
            </div>

			<?php
			if ($blockObj->isEnabled() && count($tagCloudItems)) {
				?>
                <div class="block-title" id="blog_tags">
                    <strong class="blog-sidebar-block-title"><?php echo $block->escapeHtml(__('TAGS')) ?></strong>
                </div>

                <div class="block-content blog-sidebar-block-content" id="tags_blogs">
                    <span class="toggle-menu-responsive">BLOG NAVIGATION</span>
                    <ul data-mage-init='{"awBlogToggleCategories":{}}' class="block-category-listing">
						<?php foreach ($tagCloudItems as $tagCloudItem): ?>
							<?php $indexItem++; ?>
                            <li class="block-category-listing-item <?php /* @noEscape */
							echo $block->getAdditionalClass($indexItem) ?>">
                                <a href="<?php /* @noEscape */
								echo $blockObj->escapeXssInUrl($blockObj->getSearchByTagUrl($tagCloudItem)) ?>"
                                   class="block-category-listing-item-link">
									<?php echo $blockObj->escapeHtml($tagCloudItem->getTag()->getName()) ?>
                                </a>
                            </li>
						<?php endforeach; ?>
                    </ul>
                </div>
				<?php
			}
			?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery',
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery("#BLOG_NAVIGATION").click(function () {
                var a = jQuery("#blog_navigation").css("display");
                if (a == "none") {
                    jQuery("#BLOG_NAVIGATION").addClass('active');
                    jQuery("#BLOG_NAVIGATION").focus();
                    jQuery(".block-content.blog-sidebar-block-content").addClass('active');
                    jQuery(".block-content.blog-sidebar-block-content").focus();
                } else if (a == 'block') {
                    jQuery("#BLOG_NAVIGATION").removeClass('active');
                    jQuery("#BLOG_NAVIGATION").focus();
                    jQuery(".block-content.blog-sidebar-block-content").removeClass('active');
                    jQuery(".block-content.blog-sidebar-block-content").focus();
                }
            });
        });
    });
</script>
