<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products" data-mage-init='<?= /* @escapeNotVerified */ $block->getWidgetOptionsJson() ?>'>
        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?= $block->getPagerHtml() ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
    </div>
<?php endif ?>
<script type="text/javascript">
    /*Move toolbar category*/
    require([
    "jquery",
    "swiper"
], function($, Swiper) {  
    jQuery(document).ready(function(){
      var width = jQuery(window).width();
      if(width>767)
      {
        if(jQuery('.catalog-category-view .top_toolbar .toolbar.toolbar-products').length)
        {
          jQuery('.catalog-category-view .top_toolbar .toolbar.toolbar-products').appendTo('.category-top-wrapper');
        }

        if(jQuery('.catalogsearch-result-index .top_toolbar .toolbar.toolbar-products').length)
        {
          jQuery('.catalogsearch-result-index .top_toolbar .toolbar.toolbar-products').appendTo('.page-title-wrapper');
        }
      }
    });
    jQuery(document).resize(function(){
      var width = jQuery(window).width();
      if(width>767)
      {
        if(jQuery('.catalog-category-view .top_toolbar .toolbar.toolbar-products').length)
        {
          jQuery('.catalog-category-view .top_toolbar .toolbar.toolbar-products').appendTo('.category-top-wrapper');
        }
        if(jQuery('.catalogsearch-result-index .top_toolbar .toolbar.toolbar-products').length)
        {
          jQuery('.catalogsearch-result-index .top_toolbar .toolbar.toolbar-products').appendTo('.page-title-wrapper');
        }
      }     
    });
})
</script>