<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php $parentItem = $block->getItem() ?>
<?php $items = $block->getChildren($parentItem) ?>
<?php $_index = 0 ?>
<?php $_order = $block->getItem()->getOrder(); ?>

<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php
        // As part of invoice item renderer logic, the order is set on each invoice item.
        // In the case of a bundle product, this template takes over rendering its children,
        // so it is necessary to pass the order along to each child.
        $_item->setOrder($_order);
    ?>

    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr class="bundle-option-label">
                <td colspan="5" style="padding-left:10px;">
                    <strong><em><?= /* @escapeNotVerified */  $attributes['option_label'] ?></em></strong>
                </td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <tr class="bundle-item bundle-parent">
            <td class="item-info">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
			</td>
			<td>
                <p class="sku"><?= $block->escapeHtml($block->getSku($_item)) ?></p>
            </td>
    <?php else: ?>
        <tr class="bundle-item bundle-option-value">
            <td class="item-info" style="padding-left:10px;">
                <p><?= $block->getValueHtml($_item) ?></p>
            </td>
			<td></td>
			<td style="text-align:center;">
				<?php  
					$price = strip_tags($block->getItemPrice($_item));
					$price = explode('$',$price);
					$price1 = (real) $price[1];
					$qty = (int) $_item->getQty();
					$total = number_format($price1/$qty,2);
					echo $price[0].'$'.$total;
				?>
			</td>
            <td class="item-qty">
                <?php if ($block->canShowPriceInfo($_item)): ?>
                    <?= /* @escapeNotVerified */  $_item->getQty() * 1 ?>
                <?php else: ?>
                    &nbsp;
                <?php endif; ?>
            </td>
            <td class="item-price">
                <?php if ($block->canShowPriceInfo($_item)): ?>
                    <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
                <?php else: ?>
                    &nbsp;
                <?php endif; ?>
            </td>
    <?php endif; ?>
			
        </tr>

<?php endforeach; ?>
<tr><td colspan="6" style="border-bottom:solid 1px #eee"> </td></tr>
<?php if ($_showlastRow): ?>
    <tr>
        <td colspan="5" class="item-extra">
            <?php if ($block->getItemOptions()): ?>
                <dl>
                    <?php foreach ($block->getItemOptions() as $option): ?>
                        <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                                    <dd><?= /* @escapeNotVerified */  $option['value'] ?></dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
    </tr>
<?php endif; ?>
