<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
$jsonMaxOptionSeleted = [];
$cHelper = $this->helper(\Convert\Catalog\Helper\Data::class);
$isTrue = false;
?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                "controlContainer": ".field.option"
            }
        }
    }
</script>
        <fieldset class="fieldset fieldset-bundle-options">
            <legend id="customizeTitle" class="legend title">
                <span><?= /* @escapeNotVerified */ __('Customize %1', $helper->productAttribute($product, $product->getName(), 'name')) ?></span>
            </legend><br />
            <?= $block->getChildHtml('product_info_bundle_options_top') ?>
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?php
                    if(count($option->getSelections()) > 1) {
                        if($option->getMaxOption() > 0){
                            $jsonMaxOptionSeleted[$option->getId()] = $option->getMaxOption();
                            $isTrue = true;
                        }
                    }
                ?>
                <?= $block->getOptionHtml($option) ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?= /* @escapeNotVerified */ __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
<script>
var jM = <?php echo $cHelper->jsonEncoder($jsonMaxOptionSeleted) ?>;
require([
    "jquery",
], function($) {
    <?php if($isTrue) : ?>
    $('.fieldset-bundle-options input[type="checkbox"]').click(function(){
        var count = $(this).closest('.options-list').attr('data-selected'),
            dataId = $(this).data('id'),
            checked = $(this).is(":checked"),
            maxCount = jM[dataId];
        if(parseInt(maxCount) > 0){
            if(parseInt(count) === parseInt(maxCount)){
                if(checked){
                    return false;
                }else{
                    $(this).closest('.options-list').find('input[type="checkbox"]:not(:checked) + label.label').removeClass('disable');
                    $(this).closest('.options-list').attr('data-selected', parseInt(count) - 1);
                }
            }else{
                if(checked){
                    if(parseInt(count) + 1 === parseInt(maxCount)){
                        $(this).closest('.options-list').find('input[type="checkbox"]:not(:checked) + label.label').addClass('disable');
                    }
                    $(this).closest('.options-list').attr('data-selected', parseInt(count) + 1);
                }else{
                    $(this).closest('.options-list').attr('data-selected', parseInt(count) - 1);
                }
                
            }
        }
    })
    <?php endif; ?>
})
</script>