<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Xsearch
 */
?>
<?php
/**
 * @var \Amasty\Xsearch\Block\Search\Product $block
 * @var array $products
 */
$products = $block->getProducts();
// limit product in popup search
$limit = 6;
?>

<?php if (count($products)) : ?>
    <div class="amsearch-products" data-amsearch-js="products">
        <p class="amasty-xsearch-block-header">
			<?= $block->escapeHtml(__($block->getTitle())) ?>
        </p>
        <div class="amsearch-wrapper-content">
			<?php
			$a = 0;
			foreach ($products as $id => $product) :
				$a++;
				if ($a <= $limit) {
					?>
                    <div class="amsearch-item product-item" data-amsearch-js="product-item"
                         data-click-url="<?= $block->escapeUrl($product['url']) ?>">
                        <div class="amsearch-autocomplete-image">
							<?= $product['img'] ?>
                        </div>
                        <div class="amsearch-autocomplete-information">
                            <div class="information-container">
                                <div class="product details product-item-details">
                                    <a class="product-item-link"
                                       href="<?= $block->escapeUrl($block->getFullLink($product['url'])) ?>"
                                       title="<?= $block->escapeHtml($block->stripTags($product['name'])); ?>">
										<?= $product['name']; ?>
                                    </a>
									<?php if ($block->isShowDescription($product)) : ?>
                                        <div class="product description product-item-description">
											<?= $product['description'] ?>
                                        </div>
									<?php endif; ?>
									<?php if ($block->getReviews()) : ?>
										<?= $product['reviews']; ?>
									<?php endif; ?>
                                    <div class="amsearch-wrapper-inner">
										<?= $product['price'] ?>
										<?php if ($block->getAddToCart()) : ?>
                                            <div class="product actions product-item-actions" item-actions="1"
                                                 data-amsearch-js="item-actions">
                                                <div class="actions-primary">
													<?php if ($product['is_salable']) : ?>
                                                        <form id="<?= 'amasty-xsearch-product-' . $id; ?>"
                                                              data-role="tocart-form"
                                                              action="<?= $block->escapeHtml($product['cart_post_params']['action']); ?>"
                                                              method="post" class="amasty-xsearch-form"
                                                        >
                                                            <input type="hidden" name="product"
                                                                   value="<?= $block->escapeHtml($product['cart_post_params']['data']['product']); ?>">
															<?php if ($block->isRedirectToCartEnabled()) : ?>
                                                                <input type="hidden" name="return_url"
                                                                       value="<?= $block->escapeHtml($product['cart_post_params']['data']['return_url']); ?>">
															<?php endif; ?>
                                                            <input type="hidden"
                                                                   name="<?= $block->escapeHtml($block->getUlrEncodedParam()); ?>"
                                                                   value="<?= $block->escapeHtml($product['cart_post_params']['data'][$block->getUlrEncodedParam()]); ?>">
                                                            <input name="form_key"
                                                                   type="hidden"
                                                                   value="<?= $block->escapeHtml($block->getFormKey()) ?>"/>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
													<?php else : ?>
														<?php if ($product['is_salable']) : ?>
                                                            <div class="stock available">
                                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                            </div>
														<?php else : ?>
                                                            <div class="stock unavailable">
                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
														<?php endif; ?>
													<?php endif; ?>
                                                </div>

                                                <div data-role="add-to-links" class="actions-secondary">
													<?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()) : ?>
                                                        <a href="#"
                                                           class="action towishlist"
                                                           title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           aria-label="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           data-post='<?= $product['wishlist_post_params']; ?>'
                                                           data-action="add-to-wishlist"
                                                           role="button">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
													<?php endif; ?>

                                                    <a href="#"
                                                       class="action tocompare"
                                                       title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                                       aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                                       data-post='<?= $product['compare_post_params']; ?>'
                                                       role="button">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                </div>
                                            </div>
										<?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
					<?php
				}
				?>
			<?php endforeach; ?>
        </div>
		<?php if ($block->getNumResults() > $block->getLimit()) : ?>
            <div class="amsearch-more-results">
                <a href="<?= $block->escapeUrl($block->getResultUrl()) ?>"
                   title="<?= $block->escapeHtml(__('View All')) ?>"
                   class="amsearch-link">
					<?= $block->escapeHtml(__('See products in')) ?>
                    <span class="product-search-name"></span>
                </a>
            </div>
		<?php endif; ?>
        <input type="hidden" id="check_popup_search" value="1">
    </div>

    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            $('.amasty-xsearch-form').catalogAddToCart({});


            $(document).ready(function () {
                var search = $("#value_search").val();
                $('.product-search-name').html(search);

                var checkpopup = $("#check_popup_search").val();
                if (checkpopup == 1) {
                    $(".amsearch-results").css('border', '1px solid #EEEEEE');
                }
            });

            setTimeout(function(){
                var ajaxLoading = $('.amasty-xsearch-loader').hasClass('amasty-xsearch-hide');
                if (ajaxLoading == true) {
                    $('.amsearch-closes').css('pointer-events', 'unset');
                }
            }, 1500);
        });
    </script>
<?php endif; ?>
